# Generated by Django 4.1.7 on 2023-03-31 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id_carro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('problema', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=7)),
            ],
        ),
    ]
