# Generated by Django 4.1.7 on 2023-04-01 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id_pessoa',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(11)]),
        ),
    ]
