# Generated by Django 4.1.7 on 2023-04-01 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_remove_pessoa_id_pessoa_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(99999999999)]),
        ),
    ]
