# Generated by Django 4.1.7 on 2023-04-01 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_pessoa_carros_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carros.pessoa'),
        ),
    ]
